magic_triplets: ../combinatorial_search/array.c ../combinatorial_search/combinatorics.c combinatorics_basics.c
	gcc ../combinatorial_search/array.c ../combinatorial_search/combinatorics.c combinatorics_basics.c -o combinatorial_objects
