magic_triplets: ../array/array.c ../combinatorial_search/combinatorics.c combinatorics_basics.c
	gcc ../array/array.c ../combinatorial_search/combinatorics.c combinatorics_basics.c -o combinatorial_objects
